{{- if .Values.featureGates.enableInferenceSetController -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kaito.inferenceSetClusterRoleBindingName" . }}
  labels:
   {{- include "kaito.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kaito.inferenceSetClusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kaito.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
