apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kaito.roleBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaito.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kaito.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kaito.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
